In [4]:
#Example:
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# 0-D array 
import numpy as np
arr = np.array(42)
print(arr)

42


In [9]:
#1D array 
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [13]:
#2D array with 2 arrays 
import numpy as np 
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:
#3D array with 2D arrays 
import numpy as np 
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [17]:
import numpy as np 
a=arr = np.array(42)
b=arr = np.array([1,2,3,4,5])
c=arr = np.array([[1,2,3],[4,5,6]])
d=arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [20]:
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr[1])


2


In [21]:
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr[0])


1


In [22]:
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr[2]+ arr[3])

7


In [30]:
ACCESS 2D array
import numpy as np 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element on first row:",
      arr[0,1])

2nd element on first row: 2


In [33]:
#Slicing the elements from index 1 to index 5 
import numpy as np 
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [35]:
#statring index has not been mentioned.If we don't pass start its considered ()
import numpy as np 
arr = np.array([1,2,3,4,5,6,7])
print(arr[:5])

[1 2 3 4 5]


In [36]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7])
print(arr[:])

[1 2 3 4 5 6 7]


In [37]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [39]:
#Negative slicing
import numpy as np 
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [45]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [44]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]
